// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA85xttfjtpe_AFGNNbWOKSzfOxIS3zUMY',
    appId: '1:171720765352:web:620d49136ab21cacf1379d',
    messagingSenderId: '171720765352',
    projectId: 'skiplaain',
    authDomain: 'skiplaain.firebaseapp.com',
    storageBucket: 'skiplaain.firebasestorage.app',
    measurementId: 'G-PLRLTWR5P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApnbBwq8iX_yujKPpkCF8nQ9KBSOIhGa0',
    appId: '1:171720765352:android:cf99ba108c6b7b2ef1379d',
    messagingSenderId: '171720765352',
    projectId: 'skiplaain',
    storageBucket: 'skiplaain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFNWQkw5TKQMHrRNq8PahN_oEM-UGeO8w',
    appId: '1:171720765352:ios:00742314e7ad1c58f1379d',
    messagingSenderId: '171720765352',
    projectId: 'skiplaain',
    storageBucket: 'skiplaain.firebasestorage.app',
    iosBundleId: 'com.example.skiplaainPartnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFNWQkw5TKQMHrRNq8PahN_oEM-UGeO8w',
    appId: '1:171720765352:ios:00742314e7ad1c58f1379d',
    messagingSenderId: '171720765352',
    projectId: 'skiplaain',
    storageBucket: 'skiplaain.firebasestorage.app',
    iosBundleId: 'com.example.skiplaainPartnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA85xttfjtpe_AFGNNbWOKSzfOxIS3zUMY',
    appId: '1:171720765352:web:923335919e92c7e7f1379d',
    messagingSenderId: '171720765352',
    projectId: 'skiplaain',
    authDomain: 'skiplaain.firebaseapp.com',
    storageBucket: 'skiplaain.firebasestorage.app',
    measurementId: 'G-3D9WG0GLT8',
  );
}
